In [2]:
import pandas as pd
import  numpy as np

In [9]:
# importing  the data set 
df = pd.read_csv("./play_tennis.csv")
df.drop(columns=['day'],inplace=True)

In [11]:
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [12]:
# problem 1 

#outlook = sunny, temp = hot, humidity= high, wind = weak he will play or not

In [17]:
df["play"].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [32]:
ProbOfPlayYes = 9/14
ProbOfPlayNo = 5/14

In [33]:
print(ProbOfPlayYes)
print(ProbOfPlayNo)

0.6428571428571429
0.35714285714285715

In [34]:
# now creating a pivot table for the overlook attribute

pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [35]:
# now calculating the probability
ProbOvercastNo = 0/5
ProbRainNo = 2/5
ProbSunnyNo = 3/5


ProbOvercastYes = 4/9
ProbRainYes = 3/9
ProbSunnyYes = 2/9

In [36]:
# similarly for  other attributes as well

pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [37]:
ProbHighNo = 4/5
ProbNormalNo = 1/5

ProbHighYes = 3/9
ProbNormalYes = 6/9

In [38]:
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [39]:
ProbCoolNo = 1/5
ProbHotNo = 2/5
ProbMildNO = 2/5


ProbCoolYes = 3/9
ProbHotYes = 2/9
ProbMildYes = 4/9

In [40]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [41]:
ProbStrongNo = 3/5
ProbWeakNo = 2/5


ProbStrongYes = 3/9
ProbWeakYes = 6/9

In [ ]:
# outlook = sunny, tmp= hot , humidity = high , wind = weak

ProabilityOfPlayYes = ProbSunnyYes*ProbHotYes*ProbHighYes*ProbWeakYes*ProbOfPlayYes

In [43]:
ProabilityOfPlayYes

0.007054673721340387

In [44]:
ProabilityOfPlayNO = ProbSunnyNo*ProbHotNo*ProbHighNo*ProbWeakNo*ProbOfPlayNo

In [45]:
if(ProabilityOfPlayYes > ProabilityOfPlayNO):
    print("he will going to play in this condition")
else:
    print("he is not going to play at this condition")

he is not going to play at this condition